url_rewrites:
  - match:  (^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+)
    location: $l1$2$3
    status_code: 302
  - match: ^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad
    location: REJECT
    status_code: 302
  - match: ^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v\d\/player\/ad_break
    location: REJECT
    status_code: 302
  - match: ^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads
    location: REJECT
    status_code: 302
  - match: ^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking)
    location: REJECT
    status_code: 302
  - match: ^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext
    location: REJECT
    status_code: 302
mitm:
  - -redirector*.googlevideo.com
  - *.googlevideo.com
  - www.youtube.com
  - s.youtube.com
  - youtubei.googleapis.com
 